<?php

namespace Database\Seeders;

use App\Models\Tender;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class TenderSeeder extends Seeder
{
    public function run(): void
    {
        $tenders = [
            [
                'reference'      => 'CE N° 11/2026',
                'type'           => 'consultation_elargie',
                'title_fr'       => "Mission d'assistance comptable - Arrêt des états financiers 2025-2026-2027",
                'deadline_date'  => '2026-10-16',
                'deadline_time'  => '10:00:00',
                'opening_date'   => '2026-10-16',
                'opening_time'   => '10:30:00',
                'status'         => 'open',
            ],
            [
                'reference'      => 'AO N° 17/2026',
                'type'           => 'appel_offre',
                'title_fr'       => "Choix d'un bureau d'experts comptables - Inventaire physique et réévaluation légale des biens CIOK",
                'deadline_date'  => '2026-10-20',
                'deadline_time'  => '10:00:00',
                'opening_date'   => '2026-10-20',
                'opening_time'   => '10:30:00',
                'status'         => 'open',
            ],
            [
                'reference'      => 'AO N° 16/2026',
                'type'           => 'appel_offre',
                'title_fr'       => "Acquisition de deux voitures citadines hybrides (5 places) au profit de la CIOK",
                'deadline_date'  => '2026-09-17',
                'deadline_time'  => '13:00:00',
                'opening_date'   => '2026-09-17',
                'opening_time'   => '13:30:00',
                'status'         => 'closed',
            ],
            [
                'reference'      => 'AO N° 15/2026',
                'type'           => 'appel_offre',
                'title_fr'       => "Travaux de fumisterie",
                'deadline_date'  => '2026-09-17',
                'deadline_time'  => '12:00:00',
                'opening_date'   => '2026-09-17',
                'opening_time'   => '12:30:00',
                'status'         => 'closed',
            ],
            [
                'reference'      => 'AO N° 14/2026',
                'type'           => 'appel_offre',
                'title_fr'       => "Achat de gypse",
                'deadline_date'  => '2026-09-17',
                'deadline_time'  => '11:00:00',
                'opening_date'   => '2026-09-17',
                'opening_time'   => '11:30:00',
                'status'         => 'closed',
            ],
            [
                'reference'      => 'AO N° 13/2026',
                'type'           => 'appel_offre',
                'title_fr'       => "Acquisition bande en fils d'acier pour élévateur et bandes convoyeurs",
                'deadline_date'  => '2026-09-17',
                'deadline_time'  => '10:00:00',
                'opening_date'   => '2026-09-17',
                'opening_time'   => '10:30:00',
                'status'         => 'closed',
            ],
            [
                'reference'      => 'CE N° 10/2026',
                'type'           => 'consultation_elargie',
                'title_fr'       => "Achat de sacs d'emballage pour ciments",
                'deadline_date'  => '2026-08-11',
                'deadline_time'  => '10:00:00',
                'opening_date'   => '2026-08-11',
                'opening_time'   => '10:30:00',
                'status'         => 'awarded',
            ],
            [
                'reference'      => 'AO N° 12/2026',
                'type'           => 'appel_offre',
                'title_fr'       => "Achat de carburant (Gasoil)",
                'deadline_date'  => '2026-08-14',
                'deadline_time'  => '10:00:00',
                'opening_date'   => '2026-08-14',
                'opening_time'   => '10:30:00',
                'status'         => 'closed',
            ],
            [
                'reference'      => 'CE N° 09/2026',
                'type'           => 'consultation_elargie',
                'title_fr'       => "Achat de 26 000 ± 20% tonnes de coke de pétrole",
                'deadline_date'  => '2026-07-20',
                'deadline_time'  => '10:00:00',
                'opening_date'   => '2026-07-20',
                'opening_time'   => '10:30:00',
                'status'         => 'awarded',
            ],
            [
                'reference'      => 'CE N° 08/2026',
                'type'           => 'consultation_elargie',
                'title_fr'       => "Achat de 26 000 ± 20% tonnes de coke de pétrole",
                'deadline_date'  => '2026-07-11',
                'deadline_time'  => '10:00:00',
                'opening_date'   => '2026-07-11',
                'opening_time'   => '10:30:00',
                'status'         => 'awarded',
            ],
            [
                'reference'      => 'CE N° 07/2026',
                'type'           => 'consultation_elargie',
                'title_fr'       => "Achat de 26 000 ± 20% tonnes de coke de pétrole",
                'deadline_date'  => '2026-06-26',
                'deadline_time'  => '10:00:00',
                'opening_date'   => '2026-06-26',
                'opening_time'   => '10:30:00',
                'status'         => 'awarded',
            ],
            [
                'reference'      => 'AON - Co-commissaire aux comptes',
                'type'           => 'appel_offre',
                'title_fr'       => "Choix d'un co-commissaire aux comptes pour la période 2025-2026-2027",
                'deadline_date'  => '2026-07-03',
                'deadline_time'  => '13:00:00',
                'opening_date'   => null,
                'opening_time'   => null,
                'status'         => 'closed',
            ],
            [
                'reference'      => 'AO N° 11/2026',
                'type'           => 'appel_offre',
                'title_fr'       => "Travaux de fumisterie",
                'deadline_date'  => '2026-06-24',
                'deadline_time'  => '11:00:00',
                'opening_date'   => '2026-06-24',
                'opening_time'   => '11:30:00',
                'status'         => 'awarded',
            ],
            [
                'reference'      => 'AO N° 10/2026',
                'type'           => 'appel_offre',
                'title_fr'       => "Expertise du patrimoine",
                'deadline_date'  => '2026-06-24',
                'deadline_time'  => '10:00:00',
                'opening_date'   => '2026-06-24',
                'opening_time'   => '10:30:00',
                'status'         => 'awarded',
            ],
            [
                'reference'      => 'AO N° 09/2026',
                'type'           => 'appel_offre',
                'title_fr'       => "Achat des briques et bétons réfractaires",
                'deadline_date'  => '2026-06-18',
                'deadline_time'  => '10:00:00',
                'opening_date'   => '2026-06-18',
                'opening_time'   => '10:30:00',
                'status'         => 'closed',
            ],
            [
                'reference'      => 'AO N° 08/2026',
                'type'           => 'appel_offre',
                'title_fr'       => "Achat de gypse",
                'deadline_date'  => '2026-06-11',
                'deadline_time'  => '11:00:00',
                'opening_date'   => '2026-06-11',
                'opening_time'   => '11:30:00',
                'status'         => 'awarded',
            ],
            [
                'reference'      => 'AO N° 07/2026',
                'type'           => 'appel_offre',
                'title_fr'       => "Choix d'un bureau d'experts comptables - Inventaire physique et réévaluation légale",
                'deadline_date'  => '2026-06-01',
                'deadline_time'  => '12:00:00',
                'opening_date'   => '2026-06-01',
                'opening_time'   => '12:30:00',
                'status'         => 'awarded',
            ],
            [
                'reference'      => 'AO N° 06/2026',
                'type'           => 'appel_offre',
                'title_fr'       => "Acquisition solution complète de nettoyage - Aspirateur industriel fixe",
                'deadline_date'  => '2026-06-01',
                'deadline_time'  => '11:00:00',
                'opening_date'   => '2026-06-01',
                'opening_time'   => '11:30:00',
                'status'         => 'awarded',
            ],
            [
                'reference'      => 'AO N° 05/2026',
                'type'           => 'appel_offre',
                'title_fr'       => "Achat de sacs d'emballage pour ciments",
                'deadline_date'  => '2026-06-01',
                'deadline_time'  => '10:00:00',
                'opening_date'   => '2026-06-01',
                'opening_time'   => '10:30:00',
                'status'         => 'awarded',
            ],
            [
                'reference'      => 'AO N° 03/2026',
                'type'           => 'appel_offre',
                'title_fr'       => "Acquisition voiture monospace (16 places) et deux voitures citadines hybrides (5 places)",
                'deadline_date'  => '2026-02-12',
                'deadline_time'  => '10:00:00',
                'opening_date'   => '2026-02-12',
                'opening_time'   => '10:30:00',
                'status'         => 'awarded',
            ],
            [
                'reference'      => 'CE N° 06/2026',
                'type'           => 'consultation_elargie',
                'title_fr'       => "Achat de 26 000 ± 20% tonnes de coke de pétrole",
                'deadline_date'  => '2026-04-30',
                'deadline_time'  => '10:00:00',
                'opening_date'   => '2026-04-30',
                'opening_time'   => '10:30:00',
                'status'         => 'awarded',
            ],
            [
                'reference'      => 'AO N° 04/2026',
                'type'           => 'appel_offre',
                'title_fr'       => "Travaux de fumisterie",
                'deadline_date'  => '2026-04-28',
                'deadline_time'  => '10:00:00',
                'opening_date'   => '2026-04-28',
                'opening_time'   => '10:30:00',
                'status'         => 'awarded',
            ],
            [
                'reference'      => 'AO N° 02/2026',
                'type'           => 'appel_offre',
                'title_fr'       => "Achat de boulets de broyage",
                'deadline_date'  => '2026-02-12',
                'deadline_time'  => '10:00:00',
                'opening_date'   => '2026-02-12',
                'opening_time'   => '10:30:00',
                'status'         => 'awarded',
            ],
            [
                'reference'      => 'CE N° 05/2026',
                'type'           => 'consultation_elargie',
                'title_fr'       => "Chargement et transport des produits de carrières vers les concasseurs + foration",
                'deadline_date'  => '2026-03-13',
                'deadline_time'  => '10:00:00',
                'opening_date'   => '2026-03-13',
                'opening_time'   => '10:30:00',
                'status'         => 'awarded',
            ],
            [
                'reference'      => 'CE N° 04/2026',
                'type'           => 'consultation_elargie',
                'title_fr'       => "Achat et transport de 150 000 ± 20% tonnes de clinker",
                'deadline_date'  => '2026-03-05',
                'deadline_time'  => '10:00:00',
                'opening_date'   => '2026-03-05',
                'opening_time'   => '10:30:00',
                'status'         => 'awarded',
            ],
            [
                'reference'      => 'CE N° 03/2026',
                'type'           => 'consultation_elargie',
                'title_fr'       => "Prestations de services - Chargement, transport des produits de carrières et foration",
                'deadline_date'  => null,
                'deadline_time'  => null,
                'opening_date'   => null,
                'opening_time'   => null,
                'status'         => 'awarded',
            ],
            [
                'reference'      => 'CE N° 02/2026',
                'type'           => 'consultation_elargie',
                'title_fr'       => "Transport par camion de 26 000 ± 20% tonnes de coke de pétrole",
                'deadline_date'  => '2026-01-08',
                'deadline_time'  => '11:00:00',
                'opening_date'   => '2026-01-08',
                'opening_time'   => '11:30:00',
                'status'         => 'awarded',
            ],
        ];

        foreach ($tenders as $data) {
            $data['slug'] = Str::slug($data['reference']) . '-' . uniqid();
            $data['is_published'] = true;
            $data['published_at'] = now();

            Tender::create($data);
        }

        $this->command->info('✅ ' . count($tenders) . ' marchés publics importés !');
    }
}